name: linting

on: [push]

env:
  python-version: 3.11

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version to ${{ env.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.python-version }}
      - name: Install package and dev requirements
        run: |
          uv pip install .[dev]
      - name: ruff check
        run: |
          ruff check xpsdeeplearning pubplots notebooks tests utils
      - name: ruff formatting
        run: |
          ruff format --check xpsdeeplearning pubplots tests utils
      - name: mypy
        run: |
          mypy xpsdeeplearning pubplots tests utils