name: linting

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install package
        run: |
          python -m pip install --no-deps .
      - name: Install dev requirements
        run: |
          python -m pip install -r dev-requirements.txt
      - name: ruff
        run: |
          ruff xpsdeeplearning pubplots notebooks tests
      - name: ruff formatting
        run: |
          ruff format --check xpsdeeplearning pubplots notebooks tests
      - name: mypy
        run: |
          mypy xpsdeeplearning pubplots tests