name: pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install uv and set the python version to ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and dependencies
        run: |
          uv pip install ".[dev]"
          uv pip install coverage coveralls
      - name: Test with pytest
        run: |
          coverage run -m pytest -sv --show-capture=no tests 
      - name: Submit to coveralls
        continue-on-error: true
        if: "${{ matrix.python-version == '3.12'}}"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            coveralls --service=github